version: "3"
services:
  api:
    container_name: "demo"
    image: dhk01/demo:fileDownload
    build:
      context: .
      dockerfile: Dockerfile.demo
    env_file: .env
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - SERVER_PORT=3000
    expose:
      - "3000"
    volumes:
      - ./docker/demo/logs:/app/demo/logs
      - ./docker/demo/ormlogs.log:/app/demo/ormlogs.log
